// ── IMPORT ── PDF extraction, Claude extraction passes, Firestore write
import {
  driveAccessToken, setDriveAccessToken,
  apiKey,
  _allVisitsCache, _allLabsCache,
  _labCorrections,
  APP_PETS,
  bucketReset, setBucketReset,
  bucketUsed, setBucketUsed,
  pauseResolver, setPauseResolver,
  processingStop,
  pdfjs, setPdfjs,
} from './state.js';

import {
  db, doc, getDoc, setDoc, deleteDoc, writeBatch,
  collection, getDocs, query, where,
  $, showToast, showAlert, escHtml, sleep, invalidateChatContext,
} from './core.js';

import { sanitizeForFirestore, writeFileStatus, updateFileBadge } from './files.js';

// ── CONSTANTS ──
const BUCKET_LIMIT = 22000, TOKENS_PER_CALL = 2200;

// ── FETCH DRIVE FILE ──
export async function fetchDriveFileBlob(fileId) {
  const res = await fetch(
    `https://www.googleapis.com/drive/v3/files/${fileId}?alt=media`,
    { headers: { Authorization: `Bearer ${driveAccessToken}` } }
  );
  if (res.status === 401) {
    setDriveAccessToken(null);
    try { sessionStorage.removeItem('pr_drive_token'); } catch(e) {}
    // Signal the queue to stop
    const filesMod = await import('./files.js');
    filesMod.setProcessingStop?.(true);
    $('drive-dot').className = 'status-dot amber';
    $('drive-status').textContent = 'Drive token expired';
    filesMod.showDriveConnectPrompt('Drive access token expired during processing. Reconnect and re-run to continue.');
    throw new Error('Drive token expired (401) — reconnect Drive and retry');
  }
  if (!res.ok) throw new Error(`Drive fetch failed: ${res.status}`);
  return res.blob();
}

export function blobToBase64(blob) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result.split(',')[1]);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
}

// ── PDF.js ──
export async function getPdfJs() {
  if (pdfjs) return pdfjs;
  const script = document.createElement('script');
  script.src = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';
  document.head.appendChild(script);
  await new Promise((r, j) => { script.onload = r; script.onerror = j; });
  window.pdfjsLib.GlobalWorkerOptions.workerSrc =
    'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
  setPdfjs(window.pdfjsLib);
  return window.pdfjsLib;
}

export async function extractPdfText(blob) {
  try {
    const lib = await getPdfJs();
    const arrayBuffer = await blob.arrayBuffer();
    const pdf = await lib.getDocument({ data: arrayBuffer }).promise;
    let text = '';
    const maxPages = pdf.numPages;
    for (let i = 1; i <= maxPages; i++) {
      const page = await pdf.getPage(i);
      const content = await page.getTextContent();
      const lines = [];
      for (const item of content.items) {
        if (!item.str.trim()) continue;
        const x = item.transform[4];
        const y = item.transform[5];
        const existing = lines.find(l => Math.abs(l.y - y) < 3);
        if (existing) {
          existing.items.push({ x, str: item.str });
        } else {
          lines.push({ y, items: [{ x, str: item.str }] });
        }
      }
      lines.sort((a, b) => b.y - a.y);
      const pageText = lines.map(line => {
        line.items.sort((a, b) => a.x - b.x);
        return line.items.map(it => it.str).join('  ');
      }).join('\n');
      text += pageText + '\n';
    }
    return stripBoilerplate(text.trim());
  } catch (err) {
    console.warn('PDF.js extraction failed:', err);
    return '';
  }
}

export function stripBoilerplate(text) {
  if (!text) return text;
  return text
    .replace(/\n{3,}/g, '\n\n')
    .replace(/^.*(thank you for choosing|thank you for visiting|this document is confidential|for questions.*please call|please call.*to schedule|if you have.*questions.*contact|portal\..*\.com|www\..*\.com|fax:?\s*\d[\d\s\-()]+|powered by|generated by|printed (on|for)|page \d+ of \d+|confidential.*do not distribute).*$/gim, '')
    .replace(/your next appointment.*?\n/gi, '')
    .replace(/reminder:.*?\n/gi, '')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

export async function pdfPageToBase64(blob) {
  try {
    const lib = await getPdfJs();
    const arrayBuffer = await blob.arrayBuffer();
    const pdf = await lib.getDocument({ data: arrayBuffer }).promise;
    const page = await pdf.getPage(1);
    const viewport = page.getViewport({ scale: 1.5 });
    const canvas = document.createElement('canvas');
    canvas.width = viewport.width;
    canvas.height = viewport.height;
    await page.render({ canvasContext: canvas.getContext('2d'), viewport }).promise;
    return canvas.toDataURL('image/png').split(',')[1];
  } catch (err) {
    console.warn('PDF page render failed:', err);
    return null;
  }
}

// ── EXCEL PROCESSING ──
export async function processExcelFile(file) {
  if (!window.XLSX) {
    $('progress-current').textContent = `${file.name}: loading Excel parser…`;
    await new Promise((resolve, reject) => {
      const s = document.createElement('script');
      s.src = 'https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js';
      s.onload = resolve; s.onerror = reject;
      document.head.appendChild(s);
    });
  }

  $('progress-current').textContent = `${file.name}: reading spreadsheet…`;
  const blob = await fetchDriveFileBlob(file.id);
  const arrayBuffer = await blob.arrayBuffer();
  const workbook = window.XLSX.read(arrayBuffer, { type: 'array', cellDates: true });

  let spreadsheetText = '';
  for (const sheetName of workbook.SheetNames) {
    const sheet = workbook.Sheets[sheetName];
    const csv = window.XLSX.utils.sheet_to_csv(sheet, { blankrows: false });
    if (csv.trim()) spreadsheetText += `Sheet: ${sheetName}\n${csv}\n\n`;
  }

  if (!spreadsheetText.trim()) {
    await writeFileStatus(file.id, file.name, 'complete', {
      flags: [{ type: 'unknown_type', description: 'Excel file was empty' }]
    });
    return;
  }

  $('progress-current').textContent = `${file.name}: extracting lab data…`;

  const catHint = APP_PETS.find(p => (file.name || '').toLowerCase().includes(p.toLowerCase())) || (APP_PETS.length === 1 ? APP_PETS[0] : null);

  const prompt = `You are extracting veterinary lab data from a spreadsheet that may be a multi-year summary table, not a standard clinical record.

Known cats: ${APP_PETS.join(', ') || 'detect from content'}${catHint ? `\nThis file is likely for: ${catHint}` : ''}

This spreadsheet may have dates as rows and lab panel names as columns, with values in cells. Each row = one date's worth of lab results. Values may be free-text (e.g. "14/1.2", "Hct 48", "Usg 1.040 pH 7.5", "T4 1.3", "FeLV/FIV both neg").

For each date row with any lab values:
1. Create a minimal visit record with chiefComplaint "lab report" and visitClass "problem"
2. Parse ALL lab values from that row into individual lab entries
3. Clinic name comes from the date cell if present

Parse dates in any format. Strip clinic names from date cells.
Return JSON only, no explanation, no markdown:
{
  "cats": ["Felix"],
  "dates": ["2020-02-27"],
  "visits": [{"cat":"Felix","date":"2020-02-27","clinic":"Town & Country","chiefComplaint":"lab report","visitClass":"problem","synopsis":"Routine labs","narrative":"Lab visit","confidence":0.8,"flags":[]}],
  "labs": [{"cat":"Felix","test":"BUN","value":16,"unit":"mg/dL","refLow":null,"refHigh":null,"abnormal":null,"resultDate":"2020-02-27","visitDate":"2020-02-27","labName":"Chemistry","labGroup":"Chemistry"}],
  "pcr":[],"flags":[]
}

--- SPREADSHEET: ${file.name} ---
${spreadsheetText.slice(0, 18000)}`;

  const result = await callExtractionClaude([{ role: 'user', content: prompt }], 8000);
  if (!result || result.skip) {
    await writeFileStatus(file.id, file.name, 'complete', {
      flags: [{ type: 'excel_manual_review', description: 'Excel file — review required' }]
    });
    return;
  }

  const allCats = new Set(result.cats || []);
  const allDates = new Set(result.dates || []);
  const allLabs = [...(result.labs || []), ...(result.pcr || []).map(r => ({...r, labName:'PCR', labGroup:'PCR'}))];
  normalizeLabGroups(allLabs);
  const cleanLabs = stripBPFromLabs(allLabs);

  await writeExtractionToFirestore(file, result.visits || [], cleanLabs, result.flags || [], allCats, allDates, ['excel'], false, null);
}

// ── THROTTLE ──
async function throttleCheck() {
  const now = Date.now();
  if (now - bucketReset > 60000) { setBucketReset(now); setBucketUsed(0); }
  setBucketUsed(bucketUsed + TOKENS_PER_CALL);
  if (bucketUsed > BUCKET_LIMIT) {
    const waitMs = 62000 - (Date.now() - bucketReset);
    await showThrottleCountdown(Math.ceil(waitMs / 1000));
    setBucketReset(Date.now()); setBucketUsed(TOKENS_PER_CALL);
  }
}

async function showThrottleCountdown(secs) {
  for (let i = secs; i > 0; i--) {
    $('progress-current').textContent = `Rate limit — cooling down ${i}s…`;
    await sleep(1000);
  }
}

export function showPauseOverlay(filename) {
  $('pause-file-info').textContent = filename ? `Paused on: ${filename}` : 'Paused — progress so far is saved';
  $('pause-overlay').classList.add('open');
}

export function hidePauseOverlay() { $('pause-overlay').classList.remove('open'); }

export function waitForResume() {
  return new Promise(r => { setPauseResolver(r); });
}

// ── TEXT SIMILARITY (Jaccard) ──
export function textSimilarity(a, b) {
  if (!a || !b) return 0;
  const wa = new Set(a.toLowerCase().split(/\W+/).filter(w => w.length > 3));
  const wb = new Set(b.toLowerCase().split(/\W+/).filter(w => w.length > 3));
  if (!wa.size && !wb.size) return 0;
  const inter = [...wa].filter(w => wb.has(w)).length;
  const union = new Set([...wa, ...wb]).size;
  return union === 0 ? 0 : inter / union;
}

// ── SYSTEM PROMPT ──
export function getSystemExtraction() {
  return `You are a veterinary medical records parser. Extract structured data from vet records and return ONLY valid JSON with no markdown fences. The patient is the ANIMAL, not the owner or vet. Include synopsis (2-4 factual sentences), chiefComplaint, medications with supplement flag, procedures, labs with labGroup, and full narrative structured as HISTORY/PHYSICAL EXAM/ASSESSMENT/PLAN sections. If the record mentions the patient's date of birth or birth year, include it as "birthdate" in YYYY-MM-DD format (use YYYY-01-01 if only year is known) on the visit object. Never truncate or omit clinical data. IMPORTANT: For lab values, always output valid JSON — never use bare < or > characters in values. For results reported as "< 0.1" or "> 100", encode as the string "<0.1" or ">100". For qualitative results like "ADEQUATE" or "NORMAL", use the string as the value. Reference ranges with < or > should be set to null rather than including the operator.`;
}

// ── CLAUDE EXTRACTION API CALL ──
export async function callExtractionClaude(messages, maxTokens = 2000) {
  if (!apiKey) throw new Error('No API key');
  await throttleCheck();
  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01',
      'anthropic-dangerous-direct-browser-access': 'true'
    },
    body: JSON.stringify({
      model: 'claude-sonnet-4-20250514',
      max_tokens: maxTokens,
      system: getSystemExtraction(),
      messages
    })
  });

  if (res.status === 529 || res.status === 429) {
    const retryAfter = parseInt(res.headers?.get?.('retry-after') || '30');
    const wait = Math.min(retryAfter, 60) * 1000;
    $('progress-current').textContent = `Rate limited — waiting ${Math.round(wait/1000)}s…`;
    await sleep(wait);
    const res2 = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'x-api-key': apiKey, 'anthropic-version': '2023-06-01', 'anthropic-dangerous-direct-browser-access': 'true' },
      body: JSON.stringify({ model: 'claude-sonnet-4-20250514', max_tokens: maxTokens, system: getSystemExtraction(), messages })
    });
    if (res2.status === 429 || res2.status === 529) {
      showPauseOverlay($('progress-current').textContent);
      await waitForResume();
      setBucketReset(Date.now()); setBucketUsed(0);
      return callExtractionClaude(messages, maxTokens);
    }
    if (!res2.ok) { const e2 = await res2.json().catch(()=>({})); throw new Error(e2?.error?.message||`API ${res2.status}`); }
    const d2 = await res2.json();
    try {
      const d2raw = d2.content.map(b=>b.text||'').join('').trim()
        .replace(/^```json\n?|^```\n?|```$/gm,'').trim()
        .replace(/"value"\s*:\s*<\s*([\d.]+)/g, (_, n) => `"value": "<${n}"`)
        .replace(/"refLow"\s*:\s*<\s*([\d.]+)/g, () => `"refLow": null`)
        .replace(/"refHigh"\s*:\s*<\s*([\d.]+)/g, () => `"refHigh": null`);
      return JSON.parse(d2raw);
    } catch { return null; }
  }

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err?.error?.message || `API ${res.status}`);
  }
  const data = await res.json();
  if (data.usage && window.updateSessionCost) {
    window.updateSessionCost(data.usage.input_tokens || 0, data.usage.output_tokens || 0);
  }
  const raw = data.content.map(b => b.text || '').join('').trim();
  if (data.stop_reason === 'max_tokens') {
    console.warn(`Response truncated at ${maxTokens} tokens — retrying with higher limit`);
    if (maxTokens < 16000) {
      return callExtractionClaude(messages, Math.min(maxTokens * 2, 16000));
    }
    console.error('Response still truncating at 16k tokens — returning partial result');
    try {
      const partial = JSON.parse(raw.replace(/^```json\n?|^```\n?|```$/gm, '').trim());
      if (!partial.flags) partial.flags = [];
      partial.flags.push({ type: 'chunk_skipped', description: 'Response truncated at 16k tokens — some data may be missing.' });
      return partial;
    } catch {
      return { skip: false, visits: [], labs: [], pcr: [], flags: [{ type: 'chunk_skipped', description: 'Response truncated and could not be parsed.' }] };
    }
  }
  console.log('Extraction raw response (first 2000):', raw.slice(0, 2000));
  try {
    const cleaned = raw
      .replace(/^```json\n?|^```\n?|```$/gm, '')
      .trim()
      .replace(/"value"\s*:\s*<\s*([\d.]+)/g, (_, n) => `"value": "<${n}"`)
      .replace(/"refLow"\s*:\s*<\s*([\d.]+)/g, (_, n) => `"refLow": null`)
      .replace(/"refHigh"\s*:\s*<\s*([\d.]+)/g, (_, n) => `"refHigh": null`);
    return JSON.parse(cleaned);
  } catch(e) {
    console.warn('JSON parse failed:', e.message);
    console.warn('Raw response (full):', raw);
    return null;
  }
}

// ── PLAIN CLAUDE CALL ──
export async function callPlainClaude(prompt, maxTokens = 1000) {
  if (!apiKey) throw new Error('No API key');
  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01',
      'anthropic-dangerous-direct-browser-access': 'true'
    },
    body: JSON.stringify({
      model: 'claude-sonnet-4-20250514',
      max_tokens: maxTokens,
      messages: [{ role: 'user', content: prompt }]
    })
  });
  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err?.error?.message || `API ${res.status}`);
  }
  const data = await res.json();
  if (data.usage && window.updateSessionCost) {
    window.updateSessionCost(data.usage.input_tokens || 0, data.usage.output_tokens || 0);
  }
  return data.content.map(b => b.text || '').join('').trim();
}

// ── BUILD USER CONTENT ──
function buildUserContent(chunk, promptText) {
  if (chunk.isImage && chunk.imageBase64) {
    return [
      { type: 'image', source: { type: 'base64', media_type: chunk.imageMediaType || 'image/jpeg', data: chunk.imageBase64 } },
      { type: 'text', text: promptText }
    ];
  }
  return promptText + '\n\n' + (chunk.text || '');
}

// ── DETECT BULK SUMMARY ──
export async function detectBulkSummary(textSnippet) {
  const hasDateRange = /(\d{1,2}\/\d{1,2}\/\d{4}|\d{4}-\d{2}-\d{2})\s*[-–—to]+\s*(\d{1,2}\/\d{1,2}\/\d{4}|\d{4}-\d{2}-\d{2})/i.test(textSnippet);
  const dateMatches = (textSnippet.match(/\d{4}-\d{2}-\d{2}|\d{1,2}\/\d{1,2}\/\d{2,4}/g) || []);
  const hasMultipleDates = dateMatches.length > 3;
  const hasProblemList = /problem list|active diagnoses|current medications|visit history|medical history|patient history/i.test(textSnippet);
  const hasPortalExport = /medical record|visit summary|discharge summary.*\n.*discharge summary/i.test(textSnippet);
  return hasDateRange || (hasMultipleDates && (hasProblemList || hasPortalExport));
}

// ── SPLIT BY DATE ──
export async function splitByDate(fullText) {
  const datePattern = /(?:^|\n)(?:Date of Service|Service Date|Visit Date|DOS|Date|Appointment Date|Exam Date|Discharge Date):\s*(\d{1,2}\/\d{1,2}\/\d{2,4}|\d{4}-\d{2}-\d{2})/gi;
  const standaloneDatePattern = /(?:^|\n)(\d{1,2}\/\d{1,2}\/\d{4})\s*\n/g;

  const splitPoints = new Set();
  let match;
  while ((match = datePattern.exec(fullText)) !== null) {
    if (match.index > 100) splitPoints.add(match.index);
  }
  while ((match = standaloneDatePattern.exec(fullText)) !== null) {
    if (match.index > 100) splitPoints.add(match.index);
  }

  const sortedPoints = [...splitPoints].sort((a, b) => a - b);
  if (sortedPoints.length < 2) return [fullText];

  const splits = [];
  let lastIdx = 0;
  for (const pt of sortedPoints) {
    if (pt > lastIdx + 100) {
      splits.push(fullText.slice(lastIdx, pt));
      lastIdx = pt;
    }
  }
  splits.push(fullText.slice(lastIdx));
  return splits.filter(s => s.trim().length > 100);
}

// ── LAB GROUP NORMALIZER ──
const BP_TESTS = new Set([
  'systolic blood pressure','diastolic blood pressure','mean arterial pressure',
  'blood pressure','systolic','diastolic'
]);

export function normalizeLabGroups(labs) {
  for (const lab of labs) {
    const t = (lab.test || '').toLowerCase().trim();
    if (_labCorrections[t]) { lab.labGroup = _labCorrections[t]; continue; }
    if (BP_TESTS.has(t)) { lab._isBP = true; continue; }
    if (lab.labGroup) continue;
    if (lab.labName) { lab.labGroup = lab.labName; continue; }
    lab.labGroup = 'Other';
  }
}

export function stripBPFromLabs(labs) {
  return labs.filter(l => !l._isBP);
}

// ── COMBINED EXTRACTION PASS ──
export async function runCombinedPass(file, chunk) {
  const isContinuation = chunk._isContinuation && chunk._context;
  const continuationHeader = isContinuation
    ? chunk._isBulkHistory
      ? `MULTI-VISIT HISTORY EXPORT — chunk ${(chunk._chunkIndex||0) + 1} of ${chunk._totalChunks||'?'}.
Known patient: ${chunk._context.cat || 'see document'}. Clinic: ${chunk._context.clinic || 'see document'}.

This file is a multi-year history export. Each chunk contains one or more complete dated visit records.
Extract EVERY visit in this chunk fully — with its own date, clinic, doctor, labs, medications, vitals.
Do NOT skip visits. Do NOT merge visits from different dates.
Strip any cumulative header blocks (Active Diagnoses, Problem List, Current Medications) — these are
running aggregates, not visit records.
`
      : `DOCUMENT CONTEXT — chunk ${(chunk._chunkIndex||0) + 1} of ${chunk._totalChunks||'?'} from the same file.
Patient/account: ${chunk._context.cat || 'see document'}
First visit seen: ${chunk._context.date || 'see document'} at ${chunk._context.clinic || 'see document'}

This chunk may contain a continuation of the previous visit (additional labs for the same date) OR
new visits from different dates. Use judgment: if there's a new date header, extract as a new visit.
If it's clearly a lab continuation with no new date, return visits:[] and put labs under the established date.
`
    : '';

  const filenameLower = (file.name || '').toLowerCase();
  const filenameHint = APP_PETS.length
    ? APP_PETS.filter(p => filenameLower.includes(p.toLowerCase()))
    : [];

  const prompt = `You are a veterinary medical records processor. Known pets in this account: ${APP_PETS.join(', ')||'detect from document'}${filenameHint.length ? ` — filename suggests this may be for: ${filenameHint.join(', ')}` : ''}. The cat/patient name is the ANIMAL PATIENT listed in the patient details section (with species, breed, age), NOT the owner, vet, or clinic name.
${continuationHeader}
CRITICAL — DATE ANCHORING:
All content in a document (clinical note, physical exam, assessments, AND all diagnostics including
CBC, chemistry, urinalysis, endocrinology, blood pressure) shares the single Record Date from the
document header. Use that date for every visit and every lab result unless a DIFFERENT date is
explicitly stated for a specific result. Never leave resultDate or visitDate null.
TWO-DIGIT YEARS: When dates use MM/DD/YY format, determine the correct 4-digit year from document
context (invoice headers, "Record Date" fields, surrounding dates). A two-digit year of 23 = 2023,
24 = 2024, etc. Never assign a year in the future. If the same lab values appear on two close dates
that differ only by year (e.g. 01/23/23 and 01/23/24), this is a duplicate — use the year that
matches other dates in the same document and flag the ambiguity.

CRITICAL — CAT IDENTIFICATION:
Cat name may not appear until page 2 or 3. "Patient" may be used instead of name. If name is
ambiguous, use species/breed/age fields nearby to confirm. Multiple cats in household: ${APP_PETS.join(', ')||'detect from document'}.

CLINIC NAME: Abbreviate the clinic name to be concise — strip generic words like "animal hospital",
"veterinary", "vet clinic", "cat hospital". Examples: "Morrisville Cat Hospital" → "Morrisville",
"BluePearl Emergency" → "BluePearl", "Carolina Veterinary Dermatology" → "Derm Clinic".

LAB TABLE FORMAT:
PDF extraction garbles table columns. Columns are: Test | Result | Units | Low Ref | High Ref | Qualifier
Qualifier values: H, HIGH, L, LOW, * (asterisk) → all mean abnormal. Blank = normal.
If qualifier says H/L/* but value appears within reference range, TRUST THE QUALIFIER — mark it abnormal.
Extract EVERY row. For "<N" values keep the string. Reference ranges vary by lab — use the ones in THIS document.
PCR/serology results may be buried in narrative text, not in the main lab table — extract those too.

LAB GROUPING — use ONLY these canonical group names:
  CBC — any complete blood count panel (also: Hematology, Automated CBC, IDEXX CBC, hemogram)
  Chemistry — any chemistry/biochemistry panel (also: Chem 25, Chem 27, Total Health Profile, Comprehensive Panel)
  Urinalysis — urine analysis panel
  GI Panel — TLI, PLI, cobalamin, folate
  Endocrinology — T4, TSH, Free T4, cortisol panels
  Serology — FeLV, FIV, heartworm antibody, titers
  PCR — any RealPCR or molecular panel
  Fecal — parasite screens, fecal PCR, giardia antigen
  Blood Gas — point-of-care blood gas panels
  Coagulation — PT, PTT, coagulation panels
BLOOD PRESSURE: Do NOT put in labs array. Store systolic readings in vitals.BP instead.

CANONICAL TEST NAMES — always output the canonical name regardless of how the lab printed it:
CBC: RBC, Hematocrit, Hemoglobin, MCV, MCH, MCHC, RDW, WBC, Neutrophils, % Neutrophils,
  Lymphocytes, % Lymphocytes, Monocytes, % Monocytes, Eosinophils, % Eosinophils,
  Basophils, % Basophils, Platelets, Reticulocytes, % Reticulocytes, Reticulocyte Hemoglobin, MPV, Plateletcrit, Bands, NRBC
Chemistry: Glucose, BUN, Creatinine, IDEXX SDMA, Phosphorus, Calcium, Sodium, Potassium,
  Chloride, TCO2, Anion Gap, Na:K Ratio, Total Protein, Albumin, Globulin, Albumin:Globulin Ratio,
  ALT, AST, ALP, GGT, Bilirubin - Total, Bilirubin - Conjugated, Bilirubin - Unconjugated,
  Cholesterol, Triglycerides, Amylase, Lipase, Creatine Kinase, BUN:Creatinine Ratio,
  Hemolysis Index, Lipemia Index, Icterus Index
Urinalysis: Specific Gravity, pH, Urine Protein, Glucose, Ketones, Bilirubin, Blood / Hemoglobin,
  Urobilinogen, Color, Clarity, WBC, RBC, Casts, Bacteria, Epithelial Cells, Crystals, Mucus, IDEXX Cystatin B
Endocrinology: Total T4, Free T4, TSH, Cortisol
GI Panel: TLI, PLI, Cobalamin, Folate, Feline Pancreatic Lipase
Common aliases to normalize: HCT→Hematocrit, HGB→Hemoglobin, PLT→Platelets,
  ALT (SGPT)→ALT, AST (SGOT)→AST, Alk Phosphatase→ALP, Alkphos→ALP,
  SDMA→IDEXX SDMA, BUN/Creatinine Ratio→BUN:Creatinine Ratio, A/G Ratio→Albumin:Globulin Ratio,
  Na/K Ratio→Na:K Ratio, TCO2 (Bicarbonate)→TCO2, Total Bilirubin→Bilirubin - Total,
  Absolute Neutrophils→Neutrophils, Absolute Lymphocytes→Lymphocytes,
  Absolute Monocytes→Monocytes, Absolute Eosinophils→Eosinophils, Absolute Basophils→Basophils,
  PCV→Hematocrit, Packed Cell Volume→Hematocrit, Red Blood Cells→RBC, White Blood Cells→WBC,
  Cobalamin (Vitamin B12)→Cobalamin, Vitamin B12→Cobalamin,
  Pancreatic Lipase Immunoreactivity→PLI, Trypsin-Like Immunoreactivity→TLI,
  Spec fPL→Feline Pancreatic Lipase, fPLI→Feline Pancreatic Lipase

Return JSON only, no markdown:
{"skip":false,"isAmendment":false,"cats":["Bella"],"dates":["2025-05-13"],"visits":[{"cat":"Bella","date":"2025-05-13","clinic":"City Vet","doctor":"Dr. Smith","chiefComplaint":"weight loss","synopsis":"2-4 sentence summary","medications":[{"name":"Prednisolone","dose":"5mg","frequency":"SID","route":"PO","continuing":true,"dispensed":false,"supplement":false}],"procedures":[{"name":"Cystocentesis","date":"2025-05-13","findings":"UA collected"}],"vitals":{"weight":"8.25 lbs","HR":164,"RR":50,"BCS":"4.5/9","muscleConditionScore":"1.5/4","BP":"124/124/124 mmHg"},"narrative":"HISTORY\\n[text]\\n\\nPHYSICAL EXAM\\n[text]\\n\\nASSESSMENT\\n[text]\\n\\nPLAN\\n[text]","confidence":0.9,"flags":[]}],"labs":[{"cat":"Bella","test":"BUN","value":16,"unit":"mg/dL","refLow":16,"refHigh":37,"abnormal":null,"resultDate":"2025-05-13","visitDate":"2025-05-13","labName":"Chemistry","labGroup":"Chemistry","source":null}],"pcr":[],"flags":[]}

INVOICES: Extract meds dispensed, vaccines given, procedures with dates. Store as docType:"Invoice". Set chiefComplaint to a brief clinical description. Set visitClass to "problem" unless vaccines-only.
If invoice has no clinical content → {"skip":true}

--- FILE: ${file.name} ---
`;

  const contLabel = chunk._isContinuation ? ` (diagnostics)` : '';
  if ($('progress-current')) $('progress-current').textContent = `${file.name}${contLabel}: calling Claude…`;

  const result = await callExtractionClaude([
    { role: 'user', content: buildUserContent(chunk, prompt) }
  ], 12000);

  if (!result) return null;
  if (result.skip) return 'SKIP';
  return result;
}

// ── CLARIFICATION PROMPT ──
export function promptClarification(filename, issues, fileId = null) {
  return new Promise(resolve => {
    const box = document.querySelector('.pause-box');
    const origContent = box.innerHTML;

    let html = `
      <div class="pause-icon">❓</div>
      <div class="pause-title">Clarification needed</div>
      <div class="pause-desc" style="margin-bottom:0.75rem;">
        Claude couldn't confidently identify some details in <strong>${escHtml(filename.slice(0,40))}</strong>.
        Please clarify before importing.
      </div>
      <div id="clarify-preview" style="width:100%;background:var(--surface);border:1px solid var(--border);border-radius:8px;overflow:hidden;margin-bottom:0.75rem;display:flex;align-items:center;justify-content:center;min-height:80px;">
        <span style="font-family:'JetBrains Mono',monospace;font-size:0.62rem;color:var(--ink-muted);">Loading preview…</span>
      </div>`;

    for (const issue of issues) {
      html += `<div style="margin-bottom:0.75rem;text-align:left;">
        <div style="font-family:'JetBrains Mono',monospace;font-size:0.65rem;color:var(--ink-dim);margin-bottom:0.35rem;">${escHtml(issue.label)}</div>`;

      if (issue.type === 'cat') {
        const catOptions = APP_PETS.length ? APP_PETS : [];
        html += `<select id="clarify-cat" style="width:100%;font-family:'JetBrains Mono',monospace;font-size:0.75rem;padding:0.4rem 0.6rem;border:1.5px solid var(--border);border-radius:7px;background:white;color:var(--ink);outline:none;margin-bottom:0.4rem;">
          <option value="">Choose existing cat…</option>
          ${catOptions.map(p => `<option value="${escHtml(p)}"${issue.current?.toLowerCase()===p.toLowerCase()?' selected':''}>${escHtml(p)}</option>`).join('')}
        </select>
        <div style="font-family:'JetBrains Mono',monospace;font-size:0.6rem;color:var(--ink-muted);margin-bottom:0.25rem;">— or enter a new cat name —</div>
        <input id="clarify-cat-new" type="text" placeholder="New cat name…" value="${escHtml(issue.current && !catOptions.some(p=>p.toLowerCase()===issue.current?.toLowerCase()) ? issue.current : '')}" style="width:100%;font-family:'JetBrains Mono',monospace;font-size:0.75rem;padding:0.4rem 0.6rem;border:1.5px solid var(--border);border-radius:7px;background:white;color:var(--ink);outline:none;">`;
      } else if (issue.type === 'date') {
        html += `<input id="clarify-date" type="date" value="${issue.current||''}" style="width:100%;font-family:'JetBrains Mono',monospace;font-size:0.75rem;padding:0.4rem 0.6rem;border:1.5px solid var(--border);border-radius:7px;background:white;color:var(--ink);outline:none;">`;
      } else if (issue.type === 'confirm') {
        html += `<div style="font-family:'JetBrains Mono',monospace;font-size:0.62rem;color:var(--ink-muted);background:var(--surface);border-radius:6px;padding:0.5rem 0.65rem;line-height:1.5;">${escHtml(issue.detail||'')}</div>
        <div style="font-family:'JetBrains Mono',monospace;font-size:0.62rem;color:var(--amber);margin-top:0.35rem;">Click "Import anyway" to proceed or "Skip file" to leave it unprocessed.</div>`;
      } else if (issue.type === 'multicat') {
        html += `<div style="font-family:'JetBrains Mono',monospace;font-size:0.62rem;color:var(--ink-muted);background:var(--surface);border-radius:6px;padding:0.5rem 0.65rem;">
          ${(issue.cats||[]).map(c => `<span style="display:inline-block;background:var(--accent);color:white;border-radius:4px;padding:0.1rem 0.4rem;margin:0.15rem;font-size:0.65rem;">${escHtml(c)}</span>`).join('')}
        </div>
        <div style="font-family:'JetBrains Mono',monospace;font-size:0.62rem;color:var(--ink-muted);margin-top:0.35rem;">If correct, click "Import anyway". Each cat's records will be stored separately.</div>`;
      }
      html += `</div>`;
    }

    html += `<div style="display:flex;gap:0.5rem;justify-content:center;margin-top:0.25rem;">
      <button id="clarify-confirm" style="flex:1;background:var(--green);color:white;border:none;border-radius:8px;font-family:'Instrument Sans',sans-serif;font-weight:600;font-size:0.9rem;padding:0.7rem;cursor:pointer;">${issues.some(i=>i.type==='confirm'||i.type==='multicat') ? 'Import anyway' : 'Import with these details'}</button>
      <button id="clarify-skip" style="background:var(--surface);color:var(--ink);border:1px solid var(--border);border-radius:8px;font-family:'Instrument Sans',sans-serif;font-size:0.85rem;padding:0.7rem 1rem;cursor:pointer;">Skip file</button>
    </div>`;

    box.innerHTML = html;

    if (fileId) {
      (async () => {
        try {
          const previewEl = document.getElementById('clarify-preview');
          if (!previewEl) return;
          const blob = await fetchDriveFileBlob(fileId);
          const ext = filename.split('.').pop().toLowerCase();
          if (ext === 'pdf' && window.pdfjsLib) {
            const arrayBuf = await blob.arrayBuffer();
            const pdf = await pdfjsLib.getDocument({ data: arrayBuf }).promise;
            const page = await pdf.getPage(1);
            const viewport = page.getViewport({ scale: 1 });
            const scale = Math.min(320 / viewport.width, 200 / viewport.height);
            const scaled = page.getViewport({ scale });
            const canvas = document.createElement('canvas');
            canvas.width = scaled.width;
            canvas.height = scaled.height;
            canvas.style.cssText = 'max-width:100%;border-radius:6px;';
            await page.render({ canvasContext: canvas.getContext('2d'), viewport: scaled }).promise;
            previewEl.innerHTML = '';
            previewEl.appendChild(canvas);
          } else {
            previewEl.innerHTML = `<span style="font-family:'JetBrains Mono',monospace;font-size:0.62rem;color:var(--ink-muted);">Preview not available — <a href="https://drive.google.com/file/d/${fileId}/view" target="_blank" style="color:var(--accent);">open in Drive ↗</a></span>`;
          }
        } catch(e) {
          const previewEl = document.getElementById('clarify-preview');
          if (previewEl) previewEl.innerHTML = `<span style="font-family:'JetBrains Mono',monospace;font-size:0.62rem;color:var(--ink-muted);">Preview failed — <a href="https://drive.google.com/file/d/${fileId}/view" target="_blank" style="color:var(--accent);">open in Drive ↗</a></span>`;
        }
      })();
    }

    const _catSel = document.getElementById('clarify-cat');
    const _catInp = document.getElementById('clarify-cat-new');
    if (_catSel && _catInp) {
      _catSel.addEventListener('change', () => { if (_catSel.value) _catInp.value = ''; });
      _catInp.addEventListener('input', () => { if (_catInp.value.trim()) _catSel.value = ''; });
    }

    $('pause-overlay').classList.add('open');

    const cleanup = (result) => {
      $('pause-overlay').classList.remove('open');
      box.innerHTML = origContent;
      const btn = document.getElementById('pause-continue-btn');
      if (btn) btn.addEventListener('click', () => {
        if (pauseResolver) { pauseResolver(); setPauseResolver(null); }
        hidePauseOverlay();
      });
      resolve(result);
    };

    document.getElementById('clarify-confirm').onclick = () => {
      const corrections = {};
      const catEl = document.getElementById('clarify-cat');
      const catNewEl = document.getElementById('clarify-cat-new');
      const dateEl = document.getElementById('clarify-date');
      if (catEl || catNewEl) {
        const catVal = (catEl?.value?.trim()) || (catNewEl?.value?.trim()) || '';
        if (!catVal && issues.some(i => i.type === 'cat')) {
          let errEl = document.getElementById('clarify-cat-error');
          if (!errEl) {
            errEl = document.createElement('div');
            errEl.id = 'clarify-cat-error';
            errEl.style.cssText = 'font-family:JetBrains Mono,monospace;font-size:0.65rem;color:#b91c1c;margin-top:0.3rem;';
            errEl.textContent = 'Please select or enter a cat name before importing.';
            (catNewEl || catEl).insertAdjacentElement('afterend', errEl);
          }
          return;
        }
        if (catVal) corrections.cat = catVal;
      }
      if (dateEl?.value) corrections.date = dateEl.value;
      cleanup(corrections);
    };

    document.getElementById('clarify-skip').onclick = () => cleanup(null);
  });
}

// ── CHUNK FAILURE PROMPT ──
export function promptChunkFailure(filename, chunkSize, estimatedCost) {
  return new Promise(resolve => {
    document.getElementById('chunk-fail-overlay')?.remove();

    const overlay = document.createElement('div');
    overlay.id = 'chunk-fail-overlay';
    overlay.style.cssText = 'position:fixed;inset:0;background:rgba(42,37,32,0.58);z-index:600;display:flex;align-items:center;justify-content:center;padding:2rem;';

    overlay.innerHTML = `
      <div style="background:white;border-radius:14px;padding:2rem;max-width:420px;width:100%;text-align:center;box-shadow:0 8px 40px rgba(42,37,32,0.2);">
        <div style="font-size:2rem;margin-bottom:0.75rem;">⚠</div>
        <div style="font-family:'Instrument Serif',serif;font-size:1.2rem;margin-bottom:0.5rem;color:var(--ink);">Extraction Failed</div>
        <div style="font-size:0.82rem;color:var(--ink-muted);line-height:1.6;margin-bottom:0.35rem;">${escHtml(filename.slice(0,40))}</div>
        <div style="font-family:'JetBrains Mono',monospace;font-size:0.68rem;color:var(--ink-dim);background:var(--surface);border-radius:8px;padding:0.5rem 0.75rem;margin-bottom:1rem;">Section of ${chunkSize.toLocaleString()} chars failed twice.</div>
        <div style="font-size:0.82rem;color:var(--ink-muted);line-height:1.6;margin-bottom:1.25rem;">Splitting will retry at ~$${estimatedCost} additional cost.</div>
        <div style="display:flex;gap:0.5rem;justify-content:center;flex-wrap:wrap;">
          <button id="chunk-split-btn" style="flex:1;min-width:100px;background:var(--green);color:white;border:none;border-radius:8px;font-family:'Instrument Sans',sans-serif;font-weight:600;font-size:0.9rem;padding:0.7rem;cursor:pointer;">Split &amp; Retry</button>
          <button id="chunk-skip-btn" style="flex:1;min-width:100px;background:var(--surface);color:var(--ink);border:1px solid var(--border);border-radius:8px;font-family:'Instrument Sans',sans-serif;font-weight:600;font-size:0.9rem;padding:0.7rem;cursor:pointer;">Skip Section</button>
          <button id="chunk-abort-btn" style="flex:1;min-width:100px;background:var(--red-bg);color:var(--red);border:1px solid rgba(192,36,42,0.2);border-radius:8px;font-family:'Instrument Sans',sans-serif;font-weight:600;font-size:0.9rem;padding:0.7rem;cursor:pointer;">Abort</button>
        </div>
      </div>`;

    document.body.appendChild(overlay);

    const cleanup = (choice) => {
      overlay.remove();
      resolve(choice);
    };

    overlay.querySelector('#chunk-split-btn').onclick = () => cleanup('split');
    overlay.querySelector('#chunk-skip-btn').onclick = () => cleanup('skip');
    overlay.querySelector('#chunk-abort-btn').onclick = () => cleanup('abort');
  });
}

// ── PROCESS FILE ──
export async function processFile(file) {
  const ext = file.name.split('.').pop().toLowerCase();
  const mime = file.mimeType || '';

  // Check for cached extraction
  try {
    const cached = await getDoc(doc(db, 'extractions', file.id));
    if (cached.exists() && cached.data().result && !cached.data().committed) {
      const data = JSON.parse(cached.data().result);
      if (data.allVisits || data.allLabs) {
        showToast(`${file.name.slice(0,25)}: using cached extraction — no API cost`, 'journal');
        const allCats = new Set(data.cats || []);
        const allDates = new Set(data.dates || []);
        await writeExtractionToFirestore(file, data.allVisits||[], data.allLabs||[], data.allFlags||[], allCats, allDates, data.passes||[]);
        return;
      }
    }
  } catch(e) { /* no cache, proceed normally */ }

  await writeFileStatus(file.id, file.name, 'processing');

  // SHA-256 deduplication
  let fileHash = null;
  try {
    const blobForHash = await fetchDriveFileBlob(file.id);
    const buf = await blobForHash.arrayBuffer();
    const hashBuf = await crypto.subtle.digest('SHA-256', buf);
    fileHash = Array.from(new Uint8Array(hashBuf)).map(b => b.toString(16).padStart(2,'0')).join('');

    const dupSnap = await getDocs(query(
      collection(db, 'files'),
      where('fileHash', '==', fileHash),
      where('status', '==', 'complete')
    ));
    if (!dupSnap.empty && !dupSnap.docs.some(d => (d.data().driveFileId || d.id) === file.id)) {
      const dupDoc = dupSnap.docs[0];
      const dupFileId = dupDoc.data().driveFileId || dupDoc.id;
      const [vSnap, lSnap] = await Promise.all([
        getDocs(query(collection(db, 'visits'), where('driveFileIds', 'array-contains', dupFileId))),
        getDocs(query(collection(db, 'labs'), where('driveFileId', '==', dupFileId)))
      ]);
      const hasRecords = vSnap.size > 0 || lSnap.size > 0;
      if (hasRecords) {
        const dupName = dupDoc.data().filename || 'another file';
        showAlert(`${file.name.slice(0,40)}: duplicate of "${dupName.slice(0,30)}" (${vSnap.size} visits, ${lSnap.size} labs) — skipped`);
        await writeFileStatus(file.id, file.name, 'complete', {
          fileHash, extractionPasses: ['exact_duplicate'], duplicateOf: dupDoc.id
        });
        return;
      }
      console.log(`Duplicate hash found (${dupDoc.data().filename}) but has no records — processing anyway`);
    }
  } catch(e) { console.warn('Hash check failed (non-critical):', e.message); }

  let extractedText = null;
  let isImage = false;
  let imageBase64 = null;
  let imageMediaType = null;

  if (ext === 'xlsx' || ext === 'xls' || mime.includes('spreadsheet')) {
    await processExcelFile(file);
    return;
  } else if (['jpg','jpeg','png','gif','webp','tiff','tif'].includes(ext)) {
    isImage = true;
    const blob = await fetchDriveFileBlob(file.id);
    imageBase64 = await blobToBase64(blob);
    imageMediaType = blob.type || `image/${ext === 'jpg' ? 'jpeg' : ext}`;
  } else if (ext === 'pdf' || mime === 'application/pdf') {
    $('progress-current').textContent = `${file.name}: extracting text…`;
    const blob = await fetchDriveFileBlob(file.id);
    extractedText = await extractPdfText(blob);
    if (!extractedText || extractedText.trim().length < 50) {
      $('progress-current').textContent = `${file.name}: rendering as image…`;
      imageBase64 = await pdfPageToBase64(blob);
      imageMediaType = 'image/png';
      isImage = true;
      extractedText = null;
    }
  } else if (['txt','md','csv'].includes(ext)) {
    const blob = await fetchDriveFileBlob(file.id);
    extractedText = await blob.text();
  } else {
    await writeFileStatus(file.id, file.name, 'complete', {
      flags: [{ type: 'unknown_type', description: `Unsupported file type: ${ext}` }]
    });
    return;
  }

  // Split into chunks
  let chunks = [{ text: extractedText, imageBase64, imageMediaType, isImage }];
  if (extractedText) {
    const CHUNK_SIZE = 15000;
    if (extractedText.length > CHUNK_SIZE) {
      const isBulkSummary = await detectBulkSummary(extractedText.slice(0, 2000));
      let splitTexts = isBulkSummary ? await splitByDate(extractedText) : [extractedText];
      const finalChunks = [];
      for (const t of splitTexts) {
        if (t.length <= CHUNK_SIZE) {
          finalChunks.push(t);
        } else {
          let pos = 0;
          while (pos < t.length) {
            let end = Math.min(pos + CHUNK_SIZE, t.length);
            if (end < t.length) {
              const breakAt = t.lastIndexOf('\n\n', end);
              if (breakAt > pos + 5000) end = breakAt;
            }
            finalChunks.push(t.slice(pos, end));
            pos = end;
          }
        }
      }
      if (finalChunks.length > 1) {
        chunks = finalChunks.map((t, i) => ({ text: t, isImage: false, _chunkIndex: i, _totalChunks: finalChunks.length, _isBulkHistory: isBulkSummary }));
        $('progress-current').textContent = `${file.name}: split into ${chunks.length} chunks`;
      }
    }
  }

  const allVisits = [];
  const allLabs = [];
  const allFlags = [];
  const allCats = new Set();
  const allDates = new Set();
  const passes = [];
  let isAmendment = false;
  let chunkContext = null;

  for (let ci = 0; ci < chunks.length; ci++) {
    const chunk = chunks[ci];
    if (processingStop) break;
    if (chunks.length > 1) {
      $('progress-current').textContent = `${file.name}: chunk ${ci+1}/${chunks.length}`;
      $('progress-label').textContent = `Processing… (chunk ${ci+1}/${chunks.length})`;
    }

    if (ci > 0 && chunkContext) {
      chunk._context = chunkContext;
      chunk._isContinuation = true;
      chunk._chunkIndex = chunk._chunkIndex ?? ci;
      chunk._totalChunks = chunk._totalChunks ?? chunks.length;
      chunk._isBulkHistory = chunk._isBulkHistory ?? chunks[0]?._isBulkHistory ?? false;
    }

    const result = await runCombinedPass(file, chunk);
    if (result === 'SKIP') {
      console.log(`${file.name}: chunk skipped (no clinical content)`);
      continue;
    }
    if (!result) {
      if (chunk._retried) {
        const chunkSize = chunk.text?.length || 0;
        const estimatedCost = ((chunkSize / 4) / 1000000 * 3).toFixed(4);
        const choice = await promptChunkFailure(file.name, chunkSize, estimatedCost);
        if (choice === 'split') {
          const mid = chunk.text.lastIndexOf('\n\n', Math.floor(chunkSize / 2)) || Math.floor(chunkSize / 2);
          chunks.splice(ci + 1, 0,
            { text: chunk.text.slice(0, mid), isImage: false, _retried: false },
            { text: chunk.text.slice(mid), isImage: false, _retried: false }
          );
        } else if (choice === 'skip') {
          allFlags.push({ type: 'chunk_skipped', description: `User skipped chunk of ${chunkSize} chars`, bestGuess: null });
        } else {
          processingStop = true;
        }
        continue;
      }
      console.warn(`${file.name}: chunk failed — retrying once`);
      chunks.splice(ci + 1, 0, { ...chunk, _retried: true });
      continue;
    }
    if (result.skip) {
      console.log(`${file.name}: skipped (invoice/no clinical content)`);
      continue;
    }

    console.log(`${file.name}: extracted visits=${result.visits?.length||0} labs=${result.labs?.length||0} pcr=${result.pcr?.length||0} flags=${result.flags?.length||0}`);
    if (!result.labs?.length && (chunk.text||'').toLowerCase().match(/\b(rbc|hematocrit|hematology|creatinine|albumin|platelets|lymphocytes|chemistry)\b/)) {
      console.warn(`${file.name}: labs expected but none extracted — chunk text (first 3000 chars):`, (chunk.text||'').slice(0,3000));
    }

    (result.cats || []).forEach(c => allCats.add(c));
    (result.dates || []).forEach(d => allDates.add(d));
    if (result.visits?.length) { allVisits.push(...result.visits); passes.push('narrative'); }
    if (result.labs?.length) { allLabs.push(...result.labs); passes.push('labs'); }
    if (result.pcr?.length) { allLabs.push(...result.pcr.map(r => ({ ...r, labName: r.labName || 'PCR', labGroup: r.labGroup || 'PCR' }))); passes.push('pcr'); }
    if (result.flags?.length) allFlags.push(...result.flags);
    if (result.isAmendment) isAmendment = true;

    if (!chunkContext) {
      const v0 = result.visits?.[0];
      const cat0 = v0?.cat || result.cats?.[0] || null;
      const date0 = v0?.date || result.dates?.[0] || null;
      if (cat0 || date0) {
        chunkContext = { cat: cat0, date: date0, clinic: v0?.clinic || null, doctor: v0?.doctor || null };
      }
    } else {
      const newCat = result.visits?.[0]?.cat || result.cats?.[0];
      const newClinic = result.visits?.[0]?.clinic;
      if (newCat && !chunkContext.cat) chunkContext.cat = newCat;
      if (newClinic && !chunkContext.clinic) chunkContext.clinic = newClinic;
    }
  }

  // Reset chunk label
  if (chunks.length > 1) $('progress-label').textContent = 'Processing…';

  // Pre-write checks
  {
    const issues = [];
    const qualityFlags = [];

    const knownCatSet = new Set((APP_PETS || []).map(p => p.toLowerCase()));
    const extractedCats = [...allCats].filter(Boolean);
    const unknownCats = extractedCats.filter(c => knownCatSet.size > 0 && !knownCatSet.has(c.toLowerCase()));

    if (!extractedCats.length) {
      issues.push({ type: 'cat', label: 'Which cat is this record for?', current: null });
    } else if (knownCatSet.size > 0 && unknownCats.length) {
      issues.push({ type: 'cat', label: `Cat "${unknownCats[0]}" not in known list — confirm or correct:`, current: unknownCats[0] });
    }

    const extractedDates = allVisits.map(v => v.date).filter(d => d && d !== 'unknown');
    if (!extractedDates.length && allVisits.length > 0) {
      issues.push({ type: 'date', label: 'What is the visit date?', current: null });
    }

    const lowConfVisits = allVisits.filter(v => (v.confidence || 0.8) < 0.6);
    if (lowConfVisits.length) {
      issues.push({
        type: 'confirm',
        label: `Claude has low confidence in this extraction (${Math.round((lowConfVisits[0].confidence||0)*100)}%). Review before importing?`,
        detail: lowConfVisits[0].synopsis || lowConfVisits[0].chiefComplaint || 'No summary available'
      });
    }

    if (extractedCats.length > 1 && knownCatSet.size > 0) {
      issues.push({
        type: 'multicat',
        label: `Multiple cats found in this file: ${extractedCats.join(', ')}. Is this correct?`,
        cats: extractedCats
      });
    }

    // Duplicate/amendment detection
    if (_allVisitsCache && allVisits.length > 0) {
      for (const v of allVisits) {
        const clinicMatch = _allVisitsCache.find(e =>
          e.cat?.toLowerCase() === v.cat?.toLowerCase() &&
          e.date === v.date &&
          (!e.clinic || !v.clinic || e.clinic?.toLowerCase() === v.clinic?.toLowerCase())
        );
        if (clinicMatch) {
          const simScore = textSimilarity(v.narrative || v.synopsis || '', clinicMatch.narrative || clinicMatch.synopsis || '');
          if (simScore > 0.2) {
            v._mergeInto = clinicMatch.id;
            isAmendment = true;
          }
        }
      }

      const mergeCount = allVisits.filter(v => v._mergeInto).length;
      if (mergeCount > 0 && mergeCount === allVisits.length && allLabs.length === 0) {
        await writeFileStatus(file.id, file.name, 'complete', {
          extractionPasses: ['merged_into_existing'],
          fileHash: fileHash || null
        });
        updateFileBadge(file.id, 'complete');
        showToast(`${file.name.slice(0,30)}: merged into existing record ✓`, 'journal');
        return;
      }
    }

    // Quality flags
    const shortSynopsis = allVisits.filter(v => !v._skipDuplicate && (!v.synopsis || v.synopsis.length < 30));
    if (shortSynopsis.length) {
      qualityFlags.push({ type: 'quality_warning', description: `Synopsis missing or very short — extraction may be incomplete.`, bestGuess: null });
    }
    const shortNarrative = allVisits.filter(v => !v._skipDuplicate && v.narrative && v.narrative.length < 150);
    if (shortNarrative.length) {
      qualityFlags.push({ type: 'quality_warning', description: `Narrative unusually short (${shortNarrative[0].narrative?.length} chars) — clinical detail may be missing.`, bestGuess: null });
    }
    const textHasLabKeywords = (extractedText || '').toLowerCase().match(/\b(cbc|chemistry|hematology|urinalysis|creatinine|albumin|platelets|lymphocytes)\b/);
    if (textHasLabKeywords && allLabs.length === 0) {
      qualityFlags.push({ type: 'quality_warning', description: 'Document appears to contain lab results but none were extracted — may need reprocessing.', bestGuess: null });
    }
    if (isAmendment && _allVisitsCache) {
      const hasMatchingVisit = allVisits.some(v => _allVisitsCache.some(e => e.cat === v.cat && e.date === v.date));
      if (!hasMatchingVisit) {
        qualityFlags.push({ type: 'quality_warning', description: 'Document flagged as amendment but no existing record found — importing as new record.', bestGuess: null });
        isAmendment = false;
      }
    }

    allFlags.push(...qualityFlags);

    if (issues.length && (allVisits.length > 0 || allLabs.length > 0)) {
      const corrections = await promptClarification(file.name, issues, file.id);
      if (corrections === null) {
        await writeFileStatus(file.id, file.name, 'unprocessed');
        updateFileBadge(file.id, 'unprocessed');
        return 'skipped';
      }
      if (corrections.cat) {
        for (const v of allVisits) v.cat = corrections.cat;
        for (const l of allLabs) l.cat = corrections.cat;
        allCats.clear(); allCats.add(corrections.cat);
      }
      if (corrections.date) {
        for (const v of allVisits) if (!v.date || v.date === 'unknown') v.date = corrections.date;
        for (const l of allLabs) if (!l.resultDate) l.resultDate = corrections.date;
        allDates.add(corrections.date);
      }
    }
  }

  // Normalize labs
  normalizeLabGroups(allLabs);
  allLabs.splice(0, allLabs.length, ...stripBPFromLabs(allLabs));

  // Reconcile lab cat names from chunk context
  if (chunkContext?.cat) {
    const knownCats = new Set((APP_PETS || []).map(p => p.toLowerCase()));
    const badCats = new Set();
    for (const lab of allLabs) {
      if (!lab.cat || (knownCats.size > 0 && !knownCats.has((lab.cat || '').toLowerCase()))) {
        badCats.add(lab.cat || '(blank)');
        lab.cat = chunkContext.cat;
      }
    }
    if (badCats.size > 0) {
      allFlags.push({
        type: 'no_cats',
        description: `Labs had unrecognized cat name(s): ${[...badCats].join(', ')}. Reassigned to ${chunkContext.cat} — please verify.`,
        bestGuess: chunkContext.cat
      });
    }
    allCats.add(chunkContext.cat);
  }

  if (processingStop && !allVisits.length && !allLabs.length) {
    await writeFileStatus(file.id, file.name, 'unprocessed');
    return 'skipped';
  }

  await writeExtractionToFirestore(file, allVisits, allLabs, allFlags, allCats, allDates, passes, isAmendment, fileHash);
}

// ── WRITE EXTRACTION TO FIRESTORE ──
export async function writeExtractionToFirestore(file, allVisits, allLabs, allFlags, allCats, allDates, passes, isAmendment = false, fileHash = null) {
  // Save raw extraction result to Firestore immediately
  const extractionCache = { allVisits, allLabs, allFlags, cats: [...allCats], dates: [...allDates], passes: [...new Set(passes)] };
  try {
    await setDoc(doc(db, 'extractions', file.id), {
      fileId: file.id, filename: file.name,
      result: JSON.stringify(extractionCache).slice(0, 900000),
      createdAt: new Date().toISOString()
    });
  } catch(e) { console.warn('Extraction cache write failed (non-critical):', e.message); }

  // Clear stale flags
  try {
    const oldFlags = await getDocs(query(collection(db, 'flags'), where('fileId', '==', file.id)));
    for (const d of oldFlags.docs) await deleteDoc(d.ref);
  } catch(e) { console.warn('Flag clear failed (non-critical):', e.message); }

  const visitDates = allVisits.map(v => v.date).filter(Boolean);
  const allKnownDates = [...new Set([...allDates, ...visitDates])].sort().reverse();
  const primaryDate = allKnownDates[0] || null;

  // Pre-fetch existing visits for amendment handling
  const amendmentMatches = {};
  if (isAmendment) {
    for (const visit of allVisits) {
      if (!visit.cat || visit.cat === 'SKIP') continue;
      try {
        if (visit._mergeInto) {
          const existDoc = await getDoc(doc(db, 'visits', visit._mergeInto));
          if (existDoc.exists()) { amendmentMatches[`${visit.cat}_${visit.date}`] = existDoc; continue; }
        }
        const existingSnap = await getDocs(query(
          collection(db, 'visits'),
          where('cat', '==', visit.cat),
          where('date', '==', visit.date || 'unknown')
        ));
        if (!existingSnap.empty) { amendmentMatches[`${visit.cat}_${visit.date}`] = existingSnap.docs[0]; }
      } catch(e) { /* non-critical */ }
    }
  }

  try {
    let fsBatch = writeBatch(db);
    let fsBatchCount = 0;
    const fsFlush = async () => {
      if (fsBatchCount > 0 && fsBatchCount % 400 === 0) {
        await fsBatch.commit();
        fsBatch = writeBatch(db);
      }
    };

    for (const visit of allVisits) {
      if (!visit.cat || visit.cat === 'SKIP') continue;

      const matchKey = `${visit.cat}_${visit.date}`;
      if (isAmendment && amendmentMatches[matchKey]) {
        const existDoc = amendmentMatches[matchKey];
        const existData = existDoc.data();
        const merged = {
          synopsis: existData.synopsis || visit.synopsis,
          narrative: existData.narrative?.length > (visit.narrative?.length || 0) ? existData.narrative : (visit.narrative || existData.narrative),
          chiefComplaint: existData.chiefComplaint || visit.chiefComplaint,
          visitClass: existData.visitClass || visit.visitClass || null,
          medications: existData.medications?.length ? existData.medications : (visit.medications || []),
          procedures: existData.procedures?.length ? existData.procedures : (visit.procedures || []),
          vitals: existData.vitals || visit.vitals,
          doctor: existData.doctor || visit.doctor,
          docType: existData.docType || visit.docType,
          updatedAt: new Date().toISOString(),
          sourceFiles: [...new Set([...(existData.sourceFiles||[]), file.name])],
          driveFileIds: [...new Set([...(existData.driveFileIds||[]), file.id])]
        };
        Object.keys(merged).forEach(k => merged[k] === null && delete merged[k]);
        fsBatch.update(existDoc.ref, sanitizeForFirestore(merged));
        if (visit.cat) allCats.add(visit.cat);
        if (visit.date) allDates.add(visit.date);
        fsBatchCount++; await fsFlush();
        continue;
      }

      fsBatch.set(doc(collection(db, 'visits')), sanitizeForFirestore({
        cat: visit.cat, date: visit.date || 'unknown',
        clinic: visit.clinic || null, doctor: visit.doctor || null,
        chiefComplaint: visit.chiefComplaint || null,
        visitClass: visit.visitClass || null,
        synopsis: visit.synopsis || null,
        docType: visit.docType || null,
        medications: visit.medications || [],
        procedures: visit.procedures || [], vitals: visit.vitals || null,
        narrative: visit.narrative || '',
        sourceFiles: [file.name], driveFileIds: [file.id], sourceFileId: file.id,
        visitCluster: `${visit.date||'unknown'}_${(visit.clinic||'unknown').toLowerCase().replace(/\s+/g,'_').slice(0,20)}`,
        confidence: visit.confidence || 0.8, flags: visit.flags || [],
        createdAt: new Date().toISOString()
      }));
      if (visit.cat) allCats.add(visit.cat);
      if (visit.date) allDates.add(visit.date);
      fsBatchCount++; await fsFlush();
    }

    for (const lab of allLabs) {
      if (!lab.test || lab.value === undefined || lab.value === null) continue;
      const cat = lab.cat || (allCats.size === 1 ? [...allCats][0] : null);
      if (!cat) continue;
      const resolvedDate = lab.resultDate || lab.visitDate || primaryDate;

      // Dedup: skip if an identical result already exists in Firestore,
      // unless the stored value is a string and the new one is numeric (upgrade).
      if (_allLabsCache) {
        const existing = _allLabsCache.find(l =>
          l.cat === cat && l.test === lab.test &&
          (l.resultDate === resolvedDate || l.visitDate === resolvedDate)
        );
        if (existing) {
          const newIsNumeric = typeof lab.value === 'number';
          const existingIsString = typeof existing.value === 'string';
          // Only allow write if we're upgrading a qualitative string to a numeric value
          if (!(newIsNumeric && existingIsString)) continue;
        }
      }

      fsBatch.set(doc(collection(db, 'labs')), sanitizeForFirestore({
        cat, test: lab.test, value: lab.value, unit: lab.unit || null,
        refLow: lab.refLow ?? null, refHigh: lab.refHigh ?? null, abnormal: lab.abnormal || null,
        resultDate: resolvedDate, visitDate: resolvedDate,
        labName: lab.labName || null, labGroup: lab.labGroup || null,
        source: lab.source || null,
        sourceFile: file.name, driveFileId: file.id,
        createdAt: new Date().toISOString()
      }));
      fsBatchCount++; await fsFlush();
    }

    for (const flag of allFlags) {
      fsBatch.set(doc(collection(db, 'flags')), sanitizeForFirestore({
        fileId: file.id, filename: file.name, type: flag.type || 'unclear_structure',
        description: flag.description || '', bestGuess: flag.bestGuess || null,
        options: ['Accept guess', 'Enter manually', 'View original'],
        resolved: false, resolvedAt: null, resolution: null,
        createdAt: new Date().toISOString()
      }));
      fsBatchCount++; await fsFlush();
    }

    await fsBatch.commit();

    // Invalidate labs cache via lazy import
    import('./labs.js').then(m => m.invalidateLabsCache());

    // Success — clean up extraction cache
    try { await setDoc(doc(db, 'extractions', file.id), { committed: true }, { merge: true }); } catch(e) {}

  } catch(batchErr) {
    console.error('Batch write failed:', batchErr.message);
    await writeFileStatus(file.id, file.name, 'failed', {
      error: 'Write failed — extraction cached. Click reprocess to retry write only.',
      extractionCached: true
    });
    showAlert(`Write failed for ${file.name.slice(0,25)} — extraction saved. Click reprocess to retry.`, 'warning');
    return;
  }

  // Final file status
  const ACTIONABLE_FLAG_TYPES = ['no_date', 'no_cats', 'unknown_type', 'chunk_skipped'];
  const actionableFlags = allFlags.filter(f => ACTIONABLE_FLAG_TYPES.includes(f.type));
  const hasData = allVisits.length > 0 || allLabs.length > 0;
  const finalStatus = (!hasData && allFlags.length === 0) ? 'empty'
    : actionableFlags.length > 0 ? 'flagged'
    : 'complete';
  await writeFileStatus(file.id, file.name, finalStatus, {
    cats: [...allCats],
    datesCovered: [...allDates].sort(),
    extractionPasses: [...new Set(passes)],
    flags: allFlags.map(f => f.type),
    fileHash: fileHash || null,
    processedAt: new Date().toISOString()
  });

  const catsEl = $(`cats-${file.id}`);
  if (catsEl && allCats.size) catsEl.textContent = [...allCats].join(', ');

  const ACTIONABLE_FLAG_TYPES2 = ['no_date', 'no_cats', 'unknown_type', 'chunk_skipped'];
  const newActionableCount = allFlags.filter(f => ACTIONABLE_FLAG_TYPES2.includes(f.type)).length;
  const flagCount = parseInt($('flags-count').textContent || '0') + newActionableCount;
  $('flags-count').textContent = flagCount;
  if (flagCount > 0) $('flags-btn').style.display = 'inline-flex';
}
